/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.13, 1.23, 1.81]} scale={[0.09, 0.14, 0.48]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Carpaint} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Allt i svart']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['ving-cylinder']} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Allt i svart']} position={[1.45, 0.65, 3.27]} />
      <group position={[1.32, 0.86, -2.78]} rotation={[Math.PI / 2, 0, 0]} scale={1.72}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Cylinder006_3.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cylinder006_4.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cylinder006_5.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cylinder006_6.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Cylinder006_7.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Cylinder006_8.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cylinder006_9.geometry} material={materials['Material.050']} />
      </group>
      <group position={[1.57, 1.11, -2.8]} rotation={[Math.PI / 2, 0, 0]} scale={1.72}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.052']} />
      </group>
      <group position={[1.42, 0.85, 2.21]} rotation={[Math.PI / 2, 0, 0]} scale={1.61}>
        <mesh geometry={nodes.Nut.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Nut_1.geometry} material={materials['Material.044']} />
      </group>
    </group>
  )
}

useGLTF.preload('/car.glb')
