/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/steeringwheel.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.028"]}
        position={[-0.3, 0.71, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.04, 0.01, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials["Material.026"]}
        position={[-0.29, 0.55, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.04, 0.01, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[0.19, 0.75, 0.03]}
        rotation={[1.45, -1.45, -0.12]}
        scale={[1.27, 1.27, 1.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.025"]}
        position={[-0.22, 0.4, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.04, 0.01, 0.04]}
      />
      <group
        position={[0.27, 0.96, -0.27]}
        rotation={[1.57, 0, -0.01]}
        scale={[-2.45, -2.45, -2.45]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.098"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.100"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_3.geometry}
          material={materials["Material.102"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_4.geometry}
          material={materials["Material.103"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_5.geometry}
          material={materials["Material.105"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_6.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_7.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_8.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_9.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.041"]}
        position={[0.55, 0.57, 0.1]}
        rotation={[-3.12, 1.54, 1.55]}
        scale={[0.06, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.037"]}
        position={[-0.03, 0.57, 0.1]}
        rotation={[-3.12, 1.54, 1.55]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.038"]}
        position={[0.27, 0.46, 0.1]}
        rotation={[-3.12, 1.54, 1.55]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.054"]}
        position={[0.84, 0.88, 0.12]}
        rotation={[-1.45, -1.46, -3.01]}
        scale={[0.04, 0.01, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials["Material.053"]}
        position={[0.78, 0.4, 0.12]}
        rotation={[-1.45, -1.46, -3.01]}
        scale={[0.04, 0.01, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials["Material.052"]}
        position={[0.84, 0.55, 0.12]}
        rotation={[-1.45, -1.46, -3.01]}
        scale={[0.04, 0.01, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material.050"]}
        position={[0.86, 0.71, 0.12]}
        rotation={[-1.45, -1.46, -3.01]}
        scale={[0.04, 0.01, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[0.36, 0.74, 0.03]}
        rotation={[-1.45, -1.46, -3.02]}
        scale={[1.27, 1.27, -1.27]}
      />
      <group
        position={[1.36, 1.26, 0.04]}
        rotation={[3.13, -0.08, -0.44]}
        scale={[0.07, 0.04, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials["Material.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={materials["Material.057"]}
        />
      </group>
      <group
        position={[-0.81, 1.26, 0.08]}
        rotation={[-3.11, -0.07, 0.29]}
        scale={[0.07, 0.04, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials["Material.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials["Material.068"]}
        position={[-0.56, 1.4, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.07, 0.02, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials["Material.071"]}
        position={[1.1, 1.42, 0.11]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.04, 0.01, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[-0.03, 1.46, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[0.25, 1.46, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder034.geometry}
        material={nodes.Cylinder034.material}
        position={[0.56, 1.45, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.015"]}
        position={[0.27, 1.13, 0.11]}
        rotation={[1.57, 0, -0.01]}
        scale={[0.47, 0.8, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={materials["Material.003"]}
        position={[-0.83, 1.19, 0.07]}
        rotation={[-1.51, -1.28, -1.51]}
        scale={[0.06, 0.03, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials["Material.008"]}
        position={[-0.33, 1.39, 0.15]}
        rotation={[0.22, -1.56, 2.19]}
        scale={[0.01, 0.08, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone001.geometry}
        material={materials["Material.009"]}
        position={[0.89, 1.38, 0.13]}
        rotation={[0.93, -1.37, 2.12]}
        scale={[0.01, 0.08, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0.39, 0.45, 0.12]}
        rotation={[-1.52, -1.33, -3.08]}
        scale={[0.7, 0.7, 0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder019.geometry}
        material={materials["Material.069"]}
        position={[1.1, 1.41, 0.09]}
        rotation={[-1.5, -1.37, -3.06]}
        scale={[0.07, 0.02, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials["Material.073"]}
        position={[0.89, 1.38, 0.11]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[-0.06, -0.02, -0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[0.68, 0.57, 0.12]}
        rotation={[-1.52, -1.33, -3.08]}
        scale={[0.73, 0.73, 0.73]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={nodes.Cylinder027.material}
        position={[0.11, 1.46, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group
        position={[1.08, 0.77, 0.05]}
        rotation={[3.07, -0.04, -1.56]}
        scale={[0.07, 0.04, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials["Material.063"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_2.geometry}
          material={materials["Material.062"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[0.41, 1.45, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder036.geometry}
        material={materials["lamp2.003"]}
        position={[0.7, 1.45, 0.11]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <group
        position={[-0.38, 1.09, 0.03]}
        rotation={[3.07, 0.16, -1.55]}
        scale={[0.13, 0.05, 0.13]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_1.geometry}
          material={materials["Material.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_2.geometry}
          material={materials["Material.064"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials["Material.070"]}
        position={[-0.56, 1.41, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.04, 0.01, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.076"]}
        position={[0.27, 1.45, 0.11]}
        rotation={[0.22, -1.56, 0.23]}
        scale={[0.01, 0.04, 0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus004.geometry}
        material={materials["Material.006"]}
        position={[1.37, 1.19, 0.04]}
        rotation={[1.52, -1.12, 1.53]}
        scale={[0.06, 0.03, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[-0.1, 1.46, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[0.18, 1.46, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={nodes.Cylinder033.material}
        position={[0.49, 1.46, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder029.geometry}
        material={materials["Material.099"]}
        position={[-0.29, 0.87, 0.13]}
        rotation={[-1.45, -1.46, -3.01]}
        scale={[0.04, 0.01, -0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus003.geometry}
        material={materials["Material.005"]}
        position={[1.38, 1.17, 0.04]}
        rotation={[1.52, -1.12, 1.53]}
        scale={[0.04, 0.02, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[0.09, 0.58, 0.13]}
        rotation={[-1.52, -1.33, -3.08]}
        scale={[0.71, 0.71, 0.71]}
      />
      <group
        position={[-0.52, 0.77, 0.07]}
        rotation={[3.07, -0.04, -1.56]}
        scale={[0.07, 0.04, 0.07]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials["Material.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_2.geometry}
          material={materials["Material.061"]}
        />
      </group>
      <group
        position={[0.94, 1.08, -0.01]}
        rotation={[3.07, -0.14, -1.57]}
        scale={[0.13, 0.05, 0.13]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_1.geometry}
          material={materials["Material.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_2.geometry}
          material={materials["Material.067"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials["Material.072"]}
        position={[-0.33, 1.38, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[-0.06, -0.02, -0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[0.04, 1.46, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[0.33, 1.46, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder035.geometry}
        material={nodes.Cylinder035.material}
        position={[0.62, 1.45, 0.12]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus002.geometry}
        material={materials["Material.004"]}
        position={[-0.83, 1.16, 0.07]}
        rotation={[-1.51, -1.28, -1.51]}
        scale={[0.04, 0.02, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[-0.18, 1.45, 0.13]}
        rotation={[1.45, -1.45, -0.11]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  );
}

useGLTF.preload("/steeringwheel.glb");