/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/steer.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.01, 0.23, -0.52]} rotation={[1.57, 0, 0]} scale={-4.62}>
        <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.098']} />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Plane006_3.geometry} material={materials['Material.102']} />
        <mesh geometry={nodes.Plane006_4.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Plane006_5.geometry} material={materials['Material.105']} />
        <mesh geometry={nodes.Plane006_6.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane006_7.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Plane006_8.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Plane006_9.geometry} material={materials['Material.012']} />
      </group>
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials['Material.028']}
        position={[-1.08, -0.24, 0.23]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials['Material.026']}
        position={[-1.05, -0.54, 0.23]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials['Material.025']}
        position={[-0.93, -0.82, 0.23]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials['Material.027']}
        position={[-0.15, -0.17, 0.05]}
        rotation={[1.55, -1.45, -0.01]}
        scale={2.39}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.037']}
        position={[-0.56, -0.5, 0.18]}
        rotation={[-3.1, 1.56, 1.52]}
        scale={[0.13, 0.05, 0.14]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.038']}
        position={[0, -0.71, 0.18]}
        rotation={[-3.1, 1.56, 1.52]}
        scale={[0.12, 0.04, 0.13]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.041']}
        position={[0.53, -0.49, 0.18]}
        rotation={[-3.1, 1.56, 1.52]}
        scale={[0.12, 0.04, 0.12]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials['Material.044']}
        position={[0.22, -0.73, 0.22]}
        rotation={[-1.57, -1.33, -3.14]}
        scale={1.32}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials['Material.044']}
        position={[-0.34, -0.49, 0.22]}
        rotation={[-1.57, -1.33, -3.14]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials['Material.044']}
        position={[0.78, -0.5, 0.22]}
        rotation={[-1.57, -1.33, -3.14]}
        scale={1.38}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials['Material.054']}
        position={[1.08, 0.09, 0.22]}
        rotation={[-1.56, -1.46, -3.12]}
        scale={[0.07, 0.02, -0.07]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials['Material.053']}
        position={[0.96, -0.82, 0.22]}
        rotation={[-1.56, -1.46, -3.12]}
        scale={[0.07, 0.02, -0.07]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials['Material.052']}
        position={[1.08, -0.53, 0.22]}
        rotation={[-1.56, -1.46, -3.12]}
        scale={[0.07, 0.02, -0.07]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials['Material.050']}
        position={[1.11, -0.23, 0.22]}
        rotation={[-1.56, -1.46, -3.12]}
        scale={[0.07, 0.02, -0.07]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials['Material.051']}
        position={[0.16, -0.18, 0.05]}
        rotation={[-1.56, -1.46, -3.13]}
        scale={[2.39, 2.39, -2.39]}
      />
      <group position={[2.05, 0.81, 0.1]} rotation={[3.13, -0.07, -0.44]} scale={[0.13, 0.08, 0.13]}>
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['Material.057']} />
      </group>
      <group position={[-2.03, 0.8, 0.1]} rotation={[-3.11, -0.05, 0.29]} scale={[0.13, 0.08, 0.13]}>
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.059']} />
        <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['Material.058']} />
      </group>
      <group position={[-1.49, -0.12, 0.11]} rotation={[3.07, -0.03, -1.56]} scale={[0.14, 0.08, 0.14]}>
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['Material.061']} />
      </group>
      <group position={[1.52, -0.12, 0.1]} rotation={[3.07, -0.03, -1.56]} scale={[0.14, 0.08, 0.14]}>
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Cylinder009_2.geometry} material={materials['Material.062']} />
      </group>
      <group position={[-1.23, 0.47, 0.11]} rotation={[3.07, 0.17, -1.55]} scale={[0.25, 0.08, 0.14]}>
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Cylinder010_2.geometry} material={materials['Material.064']} />
      </group>
      <group position={[1.29, 0.46, 0.1]} rotation={[3.07, -0.13, -1.57]} scale={[0.25, 0.08, 0.14]}>
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.Cylinder012_2.geometry} material={materials['Material.067']} />
      </group>
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials['Material.068']}
        position={[-1.56, 1.07, 0.19]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.13, 0.04, 0.2]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials['Material.069']}
        position={[1.56, 1.08, 0.19]}
        rotation={[-1.57, -1.37, -3.12]}
        scale={[0.13, 0.04, 0.2]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials['Material.070']}
        position={[-1.57, 1.08, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials['Material.071']}
        position={[1.56, 1.09, 0.21]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.07, 0.02, 0.07]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials['Material.072']}
        position={[-1.14, 1.02, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[-0.11, -0.03, -0.11]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials['Material.073']}
        position={[1.16, 1.02, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[-0.11, -0.03, -0.11]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Material.076']}
        position={[0, 1.16, 0.19]}
        rotation={[1.12, -1.57, 1.13]}
        scale={[0.02, 0.07, 1.01]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials.lamp}
        position={[-0.71, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials.lamp}
        position={[-0.58, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials.lamp}
        position={[-0.44, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={materials.lamp}
        position={[-0.31, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={materials.lamp}
        position={[-0.17, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={materials.lamp}
        position={[-0.03, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={materials.lamp}
        position={[0.11, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={materials.lamp2}
        position={[0.27, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={materials.lamp2}
        position={[0.4, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={materials.lamp2}
        position={[0.54, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={materials.lamp2}
        position={[0.67, 1.17, 0.21]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={materials['lamp2.003']}
        position={[0.81, 1.17, 0.21]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={materials['Material.099']}
        position={[-1.07, 0.07, 0.22]}
        rotation={[-1.56, -1.46, -3.12]}
        scale={[0.07, 0.02, -0.07]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.Material}
        position={[0.01, 0.56, 0.2]}
        rotation={[1.57, 0, 0]}
        scale={[0.89, 1.51, 0.51]}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={materials['Material.003']}
        position={[-2.07, 0.67, 0.09]}
        rotation={[-1.55, -1.28, -1.55]}
        scale={[0.11, 0.05, 0.1]}
      />
      <mesh
        geometry={nodes.Torus002.geometry}
        material={materials['Material.004']}
        position={[-2.08, 0.62, 0.1]}
        rotation={[-1.55, -1.28, -1.55]}
        scale={[0.07, 0.04, 0.07]}
      />
      <mesh
        geometry={nodes.Torus004.geometry}
        material={materials['Material.006']}
        position={[2.07, 0.68, 0.08]}
        rotation={[1.55, -1.12, 1.56]}
        scale={[0.11, 0.05, 0.1]}
      />
      <mesh
        geometry={nodes.Torus003.geometry}
        material={materials['Material.005']}
        position={[2.09, 0.64, 0.09]}
        rotation={[1.55, -1.12, 1.56]}
        scale={[0.07, 0.04, 0.07]}
      />
      <mesh
        geometry={nodes.Cone.geometry}
        material={materials['Material.008']}
        position={[-1.14, 1.04, 0.26]}
        rotation={[1.12, -1.57, 3.08]}
        scale={[0.02, 0.15, 0.02]}
      />
      <mesh
        geometry={nodes.Cone001.geometry}
        material={materials['Material.009']}
        position={[1.16, 1.03, 0.26]}
        rotation={[0.98, -1.38, 2.17]}
        scale={[0.02, 0.15, 0.02]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.lamp}
        position={[-0.86, 1.17, 0.22]}
        rotation={[1.55, -1.45, 0]}
        scale={[0.03, 0.02, 0.03]}
      />
    </group>
  )
}

useGLTF.preload('/steer.glb')
